import './globals.scss'
import {Inter} from 'next/font/google'
import React from "react";
import Navbar from "@/utils/NavBar";

const inter = Inter({subsets: ['latin']})

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({children}) {
    return (
        <html lang="en">
        <head>
            <link rel="stylesheet" href="font.css"></link>
            <title>Pokédex</title>
        </head>
        <body className={inter.className}>
        <Navbar/>
        <div className={'background'}>
            {children}
        </div>
        </body>
        </html>
    )
}
